on:
  workflow_dispatch:

env:
  PROVIDER: "xyz"

jobs:
  publish-binary:
    name: Publish binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags

      - run: source ./.github/scripts/lang-runtime-versions.sh

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.work

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8
        with:
          repo: pulumi/pulumictl
          tag: "latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@01cbe076be10ba0af7b0b9319ac490a93d3d2fcd
        with:
          args: -p 1 release --rm-dist --timeout 90m0s
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/**/*
